const SET_FILENAME = 'SET_FILENAME'
const SET_MENUVISIBLE = 'SET_MENUVISIBLE'
const SET_SETTINGVISIBLE = 'SET_SETTINGVISIBLE'
const SET_FONTSIZE = 'SET_FONTSIZE'
export default {
  SET_FILENAME,
  SET_MENUVISIBLE,
  SET_SETTINGVISIBLE,
  SET_FONTSIZE
}
